name: boilerplate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.3+2
  get_it: ^7.2.0
  lint: ^1.8.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    # - assets/
    # - assets/images/

  # fonts:
  #   - family: poppins
  #     fonts:
  #       - asset: public/assets/fonts/poppins/Poppins-Thin.ttf
  #         weight: 100
  #       - asset: public/assets/fonts/poppins/Poppins-ExtraLight.ttf
  #         weight: 200
  #       - asset: public/assets/fonts/poppins/Poppins-Light.ttf
  #         weight: 300
  #       - asset: public/assets/fonts/poppins/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: public/assets/fonts/poppins/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: public/assets/fonts/poppins/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: public/assets/fonts/poppins/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: public/assets/fonts/poppins/Poppins-ExtraBold.ttf
  #         weight: 800
  #       - asset: public/assets/fonts/poppins/Poppins-Black.ttf
  #         weight: 900
